site_name: d2spy
site_description: Python package for Data to Science Engine

repo_name: gdslab/d2spy
repo_url: https://github.com/gdslab/d2spy

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - License: license.md
  - Guides:
      - Guides: guides.md
  - API Reference:
      - api_reference.md
      - api_client module: api_client.md
      - auth module: auth.md
      - data_product module: data_product.md
      - data_product_collection module: data_product_collection.md
      - flight module: flight.md
      - flight_collection module: flight_collection.md
      - project module: project.md
      - project_collection module: project_collection.md
      - workspace module: workspace.md
  - Outreach:
      #     - Conferences: conferences.md
      - Workshops: workshops.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/d2s-logo-with-text-white.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: lime

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: true
      execute: false
      allow_errors: false

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gdslab

copyright: "&copy; 2024 <a href='https://github.com/gdslab' target='_blank' rel='noopener'>Geospatial Data Science Lab</a>"
